#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_etcd_client="0.0.1"
  jq -n --arg etcd_client "$ver_etcd_client" '{etcd_client: $etcd_client}'
}

version "$@"
